{% set name = "textnets" %}
{% set version = "0.4.11" %}
{% set hash = "907d1c8068bbdd6f11386c334d145d0a0574cbdee948437029406da42e09f18d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - textnets = textnets.cli:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - click >=7.0
    - pandas >1.1
    - cairocffi >=1.1
    - python-igraph >=0.8
    - spacy >=2.3
    - scipy >=1.5
    - toolz
    - leidenalg >=0.8
    - typing-extensions
    - cached-property

test:
  imports:
    - textnets
  requires:
    - pytest

about:
  home: https://textnets.readthedocs.io
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: 'Automated text analysis with networks'

  description: |
    textnets represents collections of texts as networks of documents and
    words. This provides novel possibilities for the visualization and analysis
    of text corpora.
  doc_url: https://textnets.readthedocs.io
  dev_url: https://github.com/jboynyc/textnets

extra:
  recipe-maintainers:
    - jboynyc
