{% set name = "textnets" %}
{% set version = "0.8.5" %}
{% set hash = "18d53cd741343c9edd7d440610830877f2f552623be38e551b4e2cba1b3e55f0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('c') }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python  # [build_platform != target_platform]
  host:
    - cython >=0.29
    - pip
    - poetry >=1.1
    - python
  run:
    - cairocffi >=1.3  # [not win]
    - leidenalg >=0.9
    - pandas >=1.5
    - pycairo >=1.21  # [win]
    - python
    - python-igraph >=0.10
    - scipy >=1.9
    - spacy >=3.4
    - toolz >=0.12
    - wasabi >=0.10

test:
  source_files:
    - tests
  imports:
    - textnets
  requires:
    - pytest
    - concepts
    - spacy-model-en_core_web_sm =3.4.0
  commands:
    - pytest

about:
  home: https://textnets.readthedocs.io
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Automated text analysis with networks

  description: |
    textnets represents collections of texts as networks of documents and
    words. This provides novel possibilities for the visualization and analysis
    of text corpora.
  doc_url: https://textnets.readthedocs.io
  dev_url: https://github.com/jboynyc/textnets

extra:
  recipe-maintainers:
    - jboynyc
