{% set name = "textnets" %}
{% set version = "0.5.2" %}
{% set hash = "bd1d2fcbaac1379fc953a7016a1b661b9948303b25f32af7a8968003d37a301d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - poetry >=1.1
    - python >=3.7
  run:
    - cached-property
    - cairocffi >=1.1
    - leidenalg >=0.8
    - pandas >=1.3
    - python >=3.7
    - python-igraph >=0.9
    - scipy >=1.7
    - spacy >=3.0
    - toolz
    - typing-extensions

test:
  imports:
    - textnets
  requires:
    - pytest

about:
  home: https://textnets.readthedocs.io
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: 'Automated text analysis with networks'

  description: |
    textnets represents collections of texts as networks of documents and
    words. This provides novel possibilities for the visualization and analysis
    of text corpora.
  doc_url: https://textnets.readthedocs.io
  dev_url: https://github.com/jboynyc/textnets

extra:
  recipe-maintainers:
    - jboynyc
