{% set name = "textnets" %}
{% set version = "0.8.1" %}
{% set hash = "100a69a1a082280fac602083c930df0bd539cda240ee505b09ff1ca25cba222b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<38]

requirements:
  host:
    - cython >=0.29
    - pip
    - poetry >=1.1
    - python
    - {{ compiler('c') }}
  run:
    - cairocffi >=1.3  # [not win]
    - leidenalg >=0.8
    - pandas >=1.4
    - pycairo >1.20  # [win]
    - python
    - python-igraph >=0.9,!=0.9.9,!=0.9.10
    - scipy >=1.8
    - spacy >=3.3
    - toolz

test:
  imports:
    - textnets
  requires:
    - pytest

about:
  home: https://textnets.readthedocs.io
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Automated text analysis with networks

  description: |
    textnets represents collections of texts as networks of documents and
    words. This provides novel possibilities for the visualization and analysis
    of text corpora.
  doc_url: https://textnets.readthedocs.io
  dev_url: https://github.com/jboynyc/textnets

extra:
  recipe-maintainers:
    - jboynyc
