{% set name = "textnets" %}
{% set version = "0.9.4" %}
{% set hash = "e35e78cadce8d50a7084a03506454cb2cf5f348932b270a55bfc9f495957df73" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<39]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python  # [build_platform != target_platform]
  host:
    - cython >=0.29
    - pip
    - poetry >=1.3
    - python
  run:
    - cairocffi >=1.6  # [not win]
    - leidenalg >=0.9
    - pandas >=2.1
    - pycairo >=1.23  # [win]
    - python
    - python-igraph >=0.10
    - scipy >=1.11
    - spacy >=3.7.2
    - toolz >=0.12
    - tqdm
    - wasabi >=1.1

test:
  imports:
    - textnets

about:
  home: https://textnets.readthedocs.io
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Automated text analysis with networks

  description: |
    textnets represents collections of texts as networks of documents and
    words. This provides novel possibilities for the visualization and analysis
    of text corpora.
  doc_url: https://textnets.readthedocs.io
  dev_url: https://github.com/jboynyc/textnets

extra:
  recipe-maintainers:
    - jboynyc
