{% set name = "textnets" %}
{% set version = "0.7.1" %}
{% set hash = "5ec5ffdc79ff10add124c0238f1a91709fb0ce02f6d186a2946106f3b7817ad3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<37]

requirements:
  host:
    - cython >=0.29
    - pip
    - poetry >=1.1
    - python
    - {{ compiler('c') }}
  run:
    - cached-property
    - cairocffi >=1.2  # [not win]
    - leidenalg >=0.8
    - pandas >=1.3
    - pycairo >1.20  # [win]
    - python
    - python-igraph >=0.9,!=0.9.9
    - scipy >=1.7
    - spacy >=3.2
    - toolz
    - typing-extensions

test:
  imports:
    - textnets
  requires:
    - pytest

about:
  home: https://textnets.readthedocs.io
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Automated text analysis with networks

  description: |
    textnets represents collections of texts as networks of documents and
    words. This provides novel possibilities for the visualization and analysis
    of text corpora.
  doc_url: https://textnets.readthedocs.io
  dev_url: https://github.com/jboynyc/textnets

extra:
  recipe-maintainers:
    - jboynyc
