conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
provider:
  linux_aarch64: default
  linux_ppc64le: default
  osx_arm64: default
test_on_native_only: true
